### ISSUE TITLE
Error: Failed to install kubectl (this is a bug in kubectl-action)

### ISSUE THREAD

**Issue by raynic35** [tale/kubectl-action#3]
Since today today i get an error in my github action when im trying to use the action "tale/kubectl-action@v1".
Has anything change or did i miss something?

Thats there error:
Installing kubectl version v1.26.1
Downloading kubectl (https://dl.k8s.io/release/v1.26.1/bin/linux/amd64/kubectl)
Error: Failed to install kubectl (this is a bug in kubectl-action): 

Thank you!

**Comment by VoytsovichP** [comment]
same here

**Comment by tale** [comment]
Hi, I temporarily broke it when switching to TypeScript, but I've reverted the `v1` tag back to `v1.0.5` which was the last working version, please tell me if this works.

**Comment by nisaChampagne** [comment]
just tested  it out and looks like its working again 👍
