### ISSUE TITLE
Permission denied with kubernetes action docker runners

### ISSUE THREAD

**Issue by sspakush** [tale/kubectl-action#4]
Hello! we used [actions-runner-controller](https://github.com/actions/actions-runner-controller) and face problem with your action: 
`/runner/_work/_temp/1c1e436f-9c53-4d58-9541-0b535446a1f0.sh: line 1: /runner/_work/_temp/b33b3809-4a30-462c-9c09-2770f6636b68/kubectl: Permission denied`
Looks like problem with permissions for kubectl =(

**Comment by tale** [comment]
Hi. This is most likely because the `kubectl` executable is not marked as a system executable. Is this issue only with the repository you are using or is it with any repository using the [actions-runner-controller](https://github.com/actions/actions-runner-controller)?

**Comment by sspakush** [comment]
With any repos which using ARC, but if we use kubectl from azure/setup-kubectl action - kubectl works fine and we don't face a problem.

**Comment by tale** [comment]
It's been fixed in the latest version, going to push a release very soon.
