### ISSUE TITLE
Issues with new V1 - what tag was v1 before Feb 3rd, 2024?

### ISSUE THREAD

**Issue by artfisica** [tale/kubectl-action#7]
Dear developers,

We have some trouble using these actions, and after multiple, multiple tests, I'd like to ask what version and/or commit `v1` was before the weekend?

I have tried until Jan 2023, but it keep failing with: 
```
File not found: '/home/github/actions-runner/_work/_actions/tale/kubectl-action/<….>/dist/index.js'
```
 
Thank you very much for your super excellent job and your help :D

**Comment by tale** [comment]
Hello, v1 pointed to release v1.2.0. Every time a new tag is published it points v1 to the new head tag.

That file exists: https://github.com/tale/kubectl-action/blob/v1/dist/index.js
